#include <3ds.h>
#include <stdio.h>

//Code auto-generated by Tebas devkitpro3ds template
int main(int argc, char **argv){
	//Initialize the graphics system with the default config
	gfxInitDefault();
	
	consoleInit(GFX_BOTTOM, NULL);
	
	printf("Hello world!\n");
	printf("Press START to exit\n");
	
	while(aptMainLoop()){
		hidScanInput();
		
		//hidKeysDown returns information about which buttons have been just pressed (and they weren't in the previous frame)
		u32 kDown = hidKeysDown();
		
		if(kDown & KEY_START){
			break; //break in order to return to hbmenu
		}
		
		//Wait for VBlank
		gspWaitForVBlank();
	}
	
	//Exit the graphics system
	gfxExit();
	return 0;
}